export const testFormFields = [
  {
    label: "User name",
    name: "cName",
    type: "text",
    placeholder: "Enter username",
    pattern: "",
    lg: 6,
    md: 6,
    sm: 12,
    xs: 12,

    //   class: "form-control form-control-line",
    //   id: "",
    //   for: "",
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "Enter email",
    pattern: "",
    lg: 6,
    md: 6,
    sm: 12,
    xs: 12,
    //   class: "form-control",
    //   id: "example-email2",
    //   for: "email",
  },
  {
    label: "Phone",
    name: "phone",
    type: "tel",
    placeholder: "Enter your phone number",
    pattern: "[0-9]{4}-[0-9]{7}",
    lg: 6,
    md: 6,
    sm: 12,
    xs: 12,
    //   class: "form-control",
    //   id: "",
    //   for: "",
  },
  {
    label: "Interview preferred time",
    name: "shift",
    type: "select",
    placeholder: "",
    pattern: "",
    lg: 6,
    md: 6,
    sm: 12,
    xs: 12,
    // class: "form-control",
    // id: "",
    // for: "",
    options: [
      {
        value: "",
        label: "--Select Option--",
      },
      {
        value: "morning",
        label: "Morning",
      },
      {
        value: "afternoon",
        label: "Afternoon",
      },
      {
        value: "evening",
        label: "Evening",
      },
    ],
  },
  {
    label: "Select Your Role (optional)",
    name: "role",
    type: "checkbox",
    placeholder: "",
    pattern: "",
    lg: 12,
    md: 12,
    sm: 12,
    xs: 12,
    //   class: "form-control",
    //   id: "",
    //   for: "",
  },
  {
    label: "",
    name: "roleVal",
    type: "radio",
    placeholder: "",
    pattern: "",
    lg: 12,
    md: 12,
    sm: 12,
    xs: 12,
    //   class: "form-control",
    //   id: "",
    //   for: "",
  },
];
